### PR TITLE
fix(wizard): remove unknown parameter in Mesh output YAML

### PR DESCRIPTION
**Pull request by jakubdyszkiewicz**
It requires an update to snapshot, but I cannot pass `yarn install` on my M1 Mac for some reason.

<Explain your change!>

Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits)

Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by johncowen** [comment]
Re-snapshotted a test here.

Screengrabs below of a before and after

### Before this PR:

Screenshot 2023-04-11 at 09 46 43

### After this PR:

Screenshot 2023-04-11 at 09 44 48

**Comment by johncowen** [comment]
@jakubdyszkiewicz not super important, but when you are around if you wanted to give me a yell and we can figure out how comes `yarn install` isn't working for you, lmk!

**Comment by johncowen** [comment]
We might want to put this onto `release-2.2`?

**Review by lahabana — APPROVED** [review]

**Comment by lahabana** [comment]
Should this be targeted at release-2.2?

**Comment by johncowen** [comment]
> Should this be targeted at release-2.2?

Yeah I think so, I just changed it, will merge shortly

**Pull request merged**
