### PR TITLE
chore: adds stylelint

### PR DESCRIPTION
**Pull request by kleinfreund**
Adds stylelint and configures the rule sets plugins for HTML, SCSS, and Vue.

Adds the `@kong/design-tokens/stylelint-plugin` plugin.

Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

### CODE REVIEW

**Review by johncowen — COMMENTED** [review]
There seem to be a few other fixes in here, is that right?

**Comment by kleinfreund** [comment]
> There seem to be a few other fixes in here, is that right?

No.

**Comment by johncowen** [comment]
What about the `$kui` variable removals? Did you remove those due to the calc?

**Comment by kleinfreund** [comment]
> What about the `$kui` variable removals? Did you remove those due to the calc?

See https://github.com/Kong/design-tokens/tree/main/stylelint-plugin. TL;DR: The stylelint plugin disallows using KUI variables for unintended properties.

**Comment by johncowen** [comment]
Ah I see, it because we are using space variables for positioning, cool, lgtm then, 1 tic

**Pull request merged**
