### PR TITLE
fix(gateways): ensure gateway linking uses ids rather than names

### PR DESCRIPTION
**Pull request by johncowen**
Similar to https://github.com/kumahq/kuma-gui/pull/2380

### CODE REVIEW

**Comment by kleinfreund** [comment]
Can you please add some tests for this so we can’t mess this up anymore?

**Comment by johncowen** [comment]
Yeah sure I can do that in a follow up?

**Comment by kleinfreund** [comment]
Sure

**Review by kleinfreund — APPROVED** [review]

**Comment by johncowen** [comment]
Tests added here https://github.com/kumahq/kuma-gui/pull/2386

**Pull request merged**
