### PR TITLE
chore(deps): upgrade to Vue.js 3

### PR DESCRIPTION
**Pull request by kleinfreund**
Upgrades the project to Vue.js 3. As part of it, the project is switching to @kong/kongponents@7. The incompatible packages vue-meta and vue-prismjs have been replaced with custom logic.

Removes vue-meta. Instead, some logic was added to App.vue to generate the appropriate value for `document.title` based on the active route.

Removes vue-prismjs. Instead, a new component `CodeBlock` was added. It uses the prismjs library which was added to the project.

Restructures how the mock server is set-up during development to avoid needing to delete msw’s `mockServiceWorker.js` file during builds.

Implements #359.

Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

### CODE REVIEW

**Review by bartsmykla — COMMENTED** [review]
> Info: On the left of the screenshots is always the new, upgraded to Vue.js 3 GUI, and on the right is the old one

## Notifications

1. Enterprise button to tall
image

## Every policy, data plane, service, zone and mesh related view

1. Missing border-bottom and table header to tall
image

## `Data Plane Proxies → All/Standard/Gateway`

1. Table is not scaling down well
image

## Wizard

### Universal ([ref](https://deploy-preview-361--kuma-gui.netlify.app/#/wizard/universal-dataplane))

#### General step

Description paragraphs not styled and Choose Mesh Section has wrong margins/paddings in multiple places
image

#### Topology step

image

#### Networking step

1. image
2. image
3. Protocol select looks like it's disabled, but it's not 
image

#### Install step

1. image
2. image

### Kubernetes

Every issue from Universal applies also for Kubernetes

#### Scope Settings step

image

**Comment by kleinfreund** [comment]
@bartsmykla 

> 1. Enterprise button to tall

This is caused by a change between kongponents 6 and 7 which previously used a rule set to make the icons in buttons a certain smaller size. This rule is gone now and the icons being bigger makes the buttons be bigger. I’ve added a custom rule (they same it used to have) to our styles so that buttons generally appear in the same size.

> 1. Missing border-bottom and table header to tall

This is caused by a change between kongponents 6 and 7. Now every row but the last gets a border bottom. See also https://kongponents.konghq.com/components/table.html. In this case, I’d rather not diverge from the kongponents default style in Kuma GUI.

> 1. Table is not scaling down well

Same here. Table cells now have a `white-space: nowrap` rule which leads to this effect. Instead, tables can be scrolled now. I’ve overwritten this behavior in Kuma GUI now. However, we should perhaps consider making better use of the available screen space. I use a very large monitor and most of the screen is unused. Using a wider layout would avoid this issue entirely: the table wouldn’t need to wrap content _or_ scroll.

> Anything related to the dataplane wizard

This was caused by a change in how CSS is applied to slotted content which used throughout the wizard and some other parts of the UI. Previously, styles from a component with a slot could apply those styles to the slotted content as well. This is no longer possible because slotted content belongs to the component that is _using_ the component with the slot. I’ve addressed those issues now.

**Comment by lahabana** [comment]
LGTM did we check the getting started wizard btw?

**Comment by bartsmykla** [comment]
@lahabana yes, I did and @kleinfreund already fixed my findings

**Review by bartsmykla — COMMENTED** [review]
## Create mesh wizard
I think spacing is off and the height of select input is different than text inputs
image
image

**Comment by bartsmykla** [comment]
I have not tested Onboarding Wizard yet

**Comment by kleinfreund** [comment]
@lahabana @bartsmykla I’ve tested the onboarding wizard and found a few incorrect colors that I fixed now.

@bartsmykla The create mesh wizard looks like this in the default branch already. There are really quite a few layout/spacing issues that need to be addressed across the UI which I rather do in a separate PR given that this one is already massive.

**Review by bartsmykla — APPROVED** [review]
lgtm

**Comment by bartsmykla** [comment]
> @bartsmykla The create mesh wizard looks like this in the default branch already. There are really quite a few layout/spacing issues that need to be addressed across the UI which I rather do in a separate PR given that this one is already massive.

No problem, overall lgtm

**Comment by kleinfreund** [comment]
Turns out that a breaking change in one of our transient dependencies broke our test suite which is why it started to fail. I needed to lock that package’s version. I also updated all other dependencies again.

**Pull request merged**
