### PR TITLE
chore: adds additional error message to XAction and use it in service/policy listings

### PR DESCRIPTION
**Pull request by johncowen**
I'm using this to try and get a flake/error on a couple of tests that commonly flake, whilst it could go in, I want to keep running it until I get a flake. Also, I'm considering adding something on this PR that reruns certain tests multiple times to make any potential flakes more likely to come up in the PR.

~DO NOT MERGE!11!! No honestly, don't 😅~

---

edit: I've run this a few times, and I can't get a flake out of it. I'd rather merge this seeing as it doesn't really change any functionality and uses `XAction` (which we'll probably end up rolling out everywhere) and see if flake continue to appear over time.

### CODE REVIEW

**Comment by johncowen** [comment]
Going in for the 7th run, typically can't get it to flake 😆 

I had a quick look into the idea of tagging a test with `@flake` or something, and based on that running that one test multiple times. Initial look into that seemed like it wouldn't be trivial to do unfortunately. Considering merging this as is as it does no harm - who knows maybe just the extra code here has somehow made it so the flake doesn't happen 🤷‍♂️ .

Will run it a couple more times and see.

**Review by kleinfreund — APPROVED** [review]

**Comment by johncowen** [comment]
Just wanted to note here that I've not seen the flake that this is investigating for quite a while, which is weird especially considering we've PRed quite a bit lately. Wondering if something somewhere has indirectly affected this, maybe https://github.com/kumahq/kuma-gui/pull/2393 🤷 

Anyway, this won't silence it if it happens but instead make it easier to figure out whats happening. Lets see how it goes.

**Comment by johncowen** [comment]
Boom 💥 

https://github.com/kumahq/kuma-gui/actions/runs/8664390344/job/23760713700?pr=2433

Screenshot 2024-04-12 at 10 48 41

This flaked, and if I'm not mistaken this it doesn't include the extra message I tried to add. So either I added the message wrong or the links I thought were causing the flake, aren't actually causing the flake.

**Comment by kleinfreund** [comment]
Last resort Cypress test debugging:

```js
document.body.insertAdjacentHTML('beforeend', `
  <div style="position: fixed; z-index: 100; top: 20px; left: 20px; padding: 10px; background: tomato; pointer-events: none;">
    <pre>${JSON.stringify(error)}</pre>
  </div>
`)
```

That way, if the error does happen, you’d see it in the video recording.

**Comment by johncowen** [comment]
Its looks to me tho that we aren't catching the right error / we aren't wrapping the extra message around the error? The above code would just produce the error in the DOM rather than in the Cypress CLI output, but if we are still wrapping around the wrong error, we still won't see anything? Or did I misunderstand something there.

Ummm, I suppose TLDR on this comment is: I 'think' (but I'm not sure) that the problem is that we are wrapping the wrong error, not that we can't display a customized error message.

---

In some way I think we are one step forwards as this flake occurring without the extra error message discounts links that I thought were causing the error. Do you come to the same thinking?

**Comment by kleinfreund** [comment]
Yeah, if the flake doesn’t produce the extra error, it can’t come from non-XAction instances.

What I suggested above was meant as a workaround for not seeing errors that might occur after another error that fails the test already.

**Pull request merged**
