### PR TITLE
chore(deps-dev): remove breaking lockfile changes

### PR DESCRIPTION
**Pull request by kleinfreund**
Same approach as https://github.com/kumahq/kuma-gui/pull/1887

Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

### CODE REVIEW

**Review by johncowen — APPROVED** [review]
Did you do a manual/lock yarn to do this or did you manually edit the lockfile?

If you used `yarn` (like I did back in #1887) I'm wondering what the difference is between us running `yarn` locally and dependabot doing the upgrade. lmk

**Comment by kleinfreund** [comment]
> If you used `yarn` (like I did back in #1887) I'm wondering what the difference is between us running `yarn` locally and dependabot doing the upgrade. lmk

I manually edited the file and then ran `yarn install` to confirm it doesn’t introduce changes again. I’m not sure what the difference of Dependabot’s behavior with us doing it like this is. I think this could be a Yarn 1 specific behavior, but I haven’t looked at this too deeply.

**Comment by johncowen** [comment]
Whats your local `yarn -v`?

**Comment by kleinfreund** [comment]
1.22.19

**Comment by johncowen** [comment]
I have `1.22.21` 🤔 , I wonder if we can tell what dependabot is using (totally not urgent btw but just incase you know)

**Pull request merged**
