### PR TITLE
chore: clean up DPP list in service view

### PR DESCRIPTION
**Pull request by kleinfreund**
**feat(services): adds copy button to address cells**

**fix: data plane list toolbar items misalignment**

**fix(services): data plane proxy list layout**

Fixes the DPP list within the service detail view for external services missing its wrapping KCard.

Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

Before:

image

After:

image

### CODE REVIEW

**Review by johncowen — COMMENTED** [review]
I was confused about this one when we saw it and wondered when it got like that.

> fix: data plane list toolbar items misalignment

It got to this state here right?

https://github.com/kumahq/kuma-gui/pull/1244

?

**Comment by kleinfreund** [comment]
@johncowen There were a couple of influences breaking this layout. One was the missing KCard. In its absence, different font properties applied sizing the various toolbar items out of proportion. After fixing that, the DPP list in the service detail view and the gateway list view looked mostly fine, but the `padding: 12px` rule still caused the items to be of a different height because KSelect doesn’t grow in a stretch-aligned flex container. Removing the padding rule fixes this on our end.

**Comment by johncowen** [comment]
Right but my question was, where did it get into this state? It seemed to me to be #1244, which I'm pretty sure it was, I just wanted to see if I could get confirmation of that in case I was wrong, no problem! Oh I'd meant to approve here as well 1 sec.

**Review by johncowen — APPROVED** [review]

**Comment by kleinfreund** [comment]
> Right but my question was, where did it get into this state?

It got into this state through the removal of KCard and the addition of `padding: 12px` on the KFilter input. https://github.com/kumahq/kuma-gui/pull/1244 was pretty much unrelated to this.

**Pull request merged**
