### PR TITLE
fix: amount sometimes being incorrectly positioned

### PR DESCRIPTION
**Pull request by kleinfreund**
**fix: amount sometimes being incorrectly positioned**

Removes the absolute positioning from the nav item amount which caused it to be pulled down with an increase in bottom padding.

**chore: removes border bottom from nav items**

Removes the functionality for adding a bottom border to certain nav items and tweaks the space between groups of nav items a little to account for it.

Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

### CODE REVIEW

**Comment by johncowen** [comment]
I think this looks fine.

How much extra work would it be to put `props.routeName` as a class on each AppNavItem?

It looks like we already do `:data-testid="props.routeName"`, so could we copy that to `:class="props.routeName"` also? (or if you wanted to be extra namespace-y`:class="nav-item-${props.routeName}"`, either is fine by me)

Lmk, I'd give this a 👍 whichever way.

**Comment by kleinfreund** [comment]
> How much extra work would it be to put `props.routeName` as a class on each AppNavItem?
> 
> It looks like we already do `:data-testid="props.routeName"`, so could we copy that to `:class="props.routeName"` also? (or if you wanted to be extra namespace-y`:class="nav-item-${props.routeName}"`, either is fine by me)

That would be simple, yes. What do you want to use it for?

**Comment by kleinfreund** [comment]
> Well, it would be handy to have if we wanted to tweak a menu item from the CSS, shall we add that while we are here if its simple?

I’ve added this now.

**Comment by johncowen** [comment]
Sorry one last thing: How comes we needed to add that `|| undefined` in that last commit? I'm asking as we added that for the data-testid and not the className. Is props.routeName ever falsey?

**Comment by kleinfreund** [comment]
> Sorry one last thing: How comes we needed to add that || undefined in that last commit?

It prevents adding an empty `data-testid` to categories which don’t have a route name.

> I'm asking as we added that for the data-testid and not the className. Is props.routeName ever falsey?

I actually need to add the same protection here, too

**Pull request merged**
