### PR TITLE
fix: unflagged reference to feature-flagged route

### PR DESCRIPTION
**Pull request by kleinfreund**
Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

### CODE REVIEW

**Review by johncowen — COMMENTED** [review]
Aren't we removing the DataPlaneList component in https://github.com/kumahq/kuma-gui/pull/2211?

**Comment by kleinfreund** [comment]
> Aren't we removing the DataPlaneList component in #2211?

Yep, but I still needed access to the feature flag here now.

**Comment by johncowen** [comment]
So you want this in before the other one? Or if we get the other one in, is this no longer required?

**Comment by kleinfreund** [comment]
> So you want this in before the other one? Or if we get the other one in, is this no longer required?

The fix of this PR will still be required regardless of whether https://github.com/kumahq/kuma-gui/pull/2211 goes in first or not. It will require a small change of course to access the feature flag directly.

I just didn’t want to mix that PR and this fix.

**Review by johncowen — APPROVED** [review]

**Comment by johncowen** [comment]
Note here's what the issue looks like:

Screenshot 2024-02-27 at 10 37 24

**Pull request merged**
