### PR TITLE
feat(zone-ingress/summary-view): add config

### PR DESCRIPTION
**Pull request by schogges**
Adds the `YAML` config to the `ZoneIngressSummaryView`.
I've also removed some of the custom types that are added in the data layer to move further to the point of inferring the type from the return value.

Part of #2922

### CODE REVIEW

**Comment by johncowen** [comment]
> I've also removed some of the custom types that are added in the data layer to move further to the point of inferring the type from the return value.

Thanks for doing this ☝️ 🎉 

---

Separately, something I forgot to note before. This YAML is showing the `ZoneIngressOverview` which isn't an actual resource, its an HTTP API only thing.

Ideally here we want to show the config for the `ZoneIngress` I think, so if the aim is to show the copyable config of the thing.

It would be the equivalent of:

Screenshot 2024-11-18 at 11 39 55

I thought this little weirdness only happened for Dataplanes, but just realizing myself now that because ZoneIngress/Egresses are just Envoy instances (i.e. Dataplanes) we also have this weirdness here.

**Comment by schogges** [comment]
> Ideally here we want to show the config for the ZoneIngress I think, so if the aim is to show the copyable config of the thing.

Ah, thank you 👍 🙂

**Comment by schogges** [comment]
@johncowen I've reworked the part in the data layer and now include the `config` which is derived from `item.zoneIngress` and some more item metadata. Doing this gives the same result as and saves us making a request to `/zone-ingresses/:name` in the summary view. Please let me know what you think 🙂

**Comment by johncowen** [comment]
> Looks good to me, I think we just need to lose the availableServices which I think are added in the backend and therefore not part of the config.

Actually, we need to be intentional about what we are showing here, and then keep it consistent. I suppose the question is are we showing:

1. The `config` or;
2. The "_result_ of what your `config` has done".

Now I think about it I'm not totally sure which we want to do.

**Comment by johncowen** [comment]
Just to note down what we chatted through offline:

---

For the moment at least we decided that we would go with showing:

> The config  that is currently applied, including all the stuff that gets added by the backend (and potentially k8s)

Reasons being:

1. I think this is what we currently do everywhere else
2. Chances are the user already has the config because they just applied it (although there is a usecase of using the GUI to share the config)
3. The interesting thing is the representation of what that config has done, which the user doesn't have

We can always come back and revisit if we decide different, but we should try to be consistent as to what these panels are showing.

**Pull request merged**
