### PR TITLE
chore(*) vue upgrade command results

### PR DESCRIPTION
**Pull request by bartsmykla**
Upgraded some of the dependdencies as a result of running
`vue upgrade` command. It's not a breaking change

Signed-off-by: Bart Smykla <bartek@smykla.com>

### CODE REVIEW

**Comment by tharun208** [comment]
@bartsmykla, can we introduce `pre-commit` hooks with this pr using `husky` https://github.com/typicode/husky which runs `lint` command

**Comment by bartsmykla** [comment]
I think it's a great idea and I will look at it, as I don't know the tool :-)

Thank you this suggestion. I really appreciate it! :-)

**Comment by tharun208** [comment]
I can raise a pr for the above if you are good to go with the idea !!

**Comment by bartsmykla** [comment]
@tharun208 let's do it, and in the PR we can ask others from @kumahq/kuma-maintainers for their opinions, but I don't think they will be against it :-)

Thank you!

**Comment by tomaszwylezek** [comment]
closing in favor of #188

**Pull request closed without merging**
