### PR TITLE
chore(*) fix lints

### PR DESCRIPTION
**Pull request by tharun208**
Fixed linting across all files.

### CODE REVIEW

**Comment by nickolaev** [comment]
@tharun208 thanks for this one! Can we enable this lint as part of the CI so it does not allow merging non-compliant changes?

**Review by nickolaev — APPROVED** [review]

**Comment by tharun208** [comment]
yes, @nickolaev thinking the same. I will work on this 👍

**Comment by nickolaev** [comment]
@tharun208 please rebase to check it against CI now!

**Comment by tharun208** [comment]
@nickolaev, I rebased and it is not running the `kuma-commit` workflow

**Comment by nickolaev** [comment]
Maybe it will work on new PRs, can you please close this one and create it once again?

**Pull request closed without merging**
