### PR TITLE
fix: not determining Zone ingress/egress correctly

### PR DESCRIPTION
**Pull request by kleinfreund**
Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

### CODE REVIEW

**Review by johncowen — APPROVED** [review]
So the fix here is due to use accessing `zonesWithIngress` within the `transformToTableData` function, but previously we were calling `transformToTableData` before `zoneWithIngress` was set/updated?

I think it would be better to try to favour pure functions with less side effects when doing this sort of stuff. But as a fix for the moment this LGTM if I understood correctly.

**Comment by kleinfreund** [comment]
> I think it would be better to try to favour pure functions with less side effects when doing this sort of stuff. But as a fix for the moment this LGTM if I understood correctly.

Yeah, totally and in this case, the data isn’t used outside that function so we could easily move it in. I’ll make a change for this.

**Comment by kleinfreund** [comment]
See https://github.com/kumahq/kuma-gui/pull/977/commits/a0fcede8fefa7b1a83f298672540f426e9619595

**Comment by kleinfreund** [comment]
@johncowen Are you okay with https://github.com/kumahq/kuma-gui/pull/977/commits/a0fcede8fefa7b1a83f298672540f426e9619595?

**Review by johncowen — APPROVED** [review]
Oh sorry, yeah sure I'm good either way rn, the additional thing you added seems better also ty!

**Pull request merged**
