### PR TITLE
chore(deps): update kongponents

### PR DESCRIPTION
**Pull request by kleinfreund**
Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>

### CODE REVIEW

**Comment by johncowen** [comment]
I'm guessing the `@npm:` stuff flip-flopped back because this was a manual/local package update rather than one done by dependabot. Guessing they would get flip-flopped back again once they are involved in a dependabot upgrade? Do you know if that's the case? Just trying to figure out why the flip-flop/where the difference is.

**Comment by kleinfreund** [comment]
> I'm guessing the `@npm:` stuff flip-flopped back because this was a manual/local package update rather than one done by dependabot. Guessing they would get flip-flopped back again once they are involved in a dependabot upgrade? Do you know if that's the case? Just trying to figure out why the flip-flop/where the difference is.

I assume that is the case, yes. I have no idea what Dependabot does differently to produce a different lock file but locally, I’ve just changed the package.json version and ran `yarn install`. I also tried a slightly different variant (`yarn add @kong/kongponents@...`) but the effect was the same.

**Comment by johncowen** [comment]
Hmm yeah judging by this PR https://github.com/kumahq/kuma-gui/pull/1857 dependabot doesn't flip those weird dependencies back out. What do you think of just not committing those hunks? I'm not totally sure on that but I'm inclined to copy exactly what dependabot does if we can.

Lastly, it looks as though this specific `yarn.lock` dedupe issue (the `@npm:` one) is caused by the fact that kongponents' current versioning scheme causes issues with dependabot, and in us working around that issue we are manually upgrading kongponents, which in turn causes this specific yarn.lock flip-flopping issue. Does that line of thinking make sense to you?

**Comment by kleinfreund** [comment]
> What do you think of just not committing those hunks? I'm not totally sure on that but I'm inclined to copy exactly what dependabot does if we can.

I’m fine with that. We don’t have too much we need to update locally and eventually nothing at all at which point this should resolve itself.



> Lastly, it looks as though this specific `yarn.lock` dedupe issue (the `@npm:` one) is caused by the fact that kongponents' current versioning scheme causes issues with dependabot, and in us working around that issue we are manually upgrading kongponents, which in turn causes this specific yarn.lock flip-flopping issue. Does that line of thinking make sense to you?

This issue has nothing to do with Kongponents. You can verify this by trying to update another dependency this way: the same result will occur. It just so happens that Kongponents is the only thing we currently update manually.

**Comment by johncowen** [comment]
> You can verify this by trying to update another dependency this way: the same result will occur.

Right, but is this because we are trying to update the dependency, i.e. its not dependabot doing it?

1 sec lemme approve this also

**Comment by johncowen** [comment]
Oh wait I just took a look on another PR and its looks like its flipping it there also 🤔 .

**Comment by kleinfreund** [comment]
> Right, but is this because we are trying to update the dependency, i.e. its not dependabot doing it?

What do you mean by this?

**Review by johncowen — APPROVED** [review]

**Pull request merged**
